name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: '13 3 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain with clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run Rustfmt
        run: cargo fmt -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain with clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  build:
    name: Rust Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests (rootful)
        run: sudo -E env "PATH=$PATH" bash tests/run_nft_tests.sh
